volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  nats_data:
    driver: local
  main_certs_data:
    driver: local

services:
  db:
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_db:latest
    labels:
      - "io.containers.autoupdate=image"
    restart: always
    shm_size: 256mb
    command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      TZ: Asia/Shanghai
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${EXTERNAL_DB_PORT:-5432}:5432
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_redis:latest
    labels:
      - "io.containers.autoupdate=image"
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  minio:
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_minio:latest
    labels:
      - "io.containers.autoupdate=image"
    command: "server /data"
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - minio_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nats:
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_nats:latest
    labels:
      - "io.containers.autoupdate=image"
    command: "-js -c /etc/nats/nats-server.conf"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - nats_data:/data/jetstream
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  main:
    build:
      context: ..
      dockerfile: docker/main/DockerfileProd
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_main_prod:latest
    labels:
      - "io.containers.autoupdate=image"
    restart: always
    logging:
      options:
        mode: non-blocking
        max-size: "20m"
        max-file: "10"
    tty: true
    depends_on:
      - minio
      - nats
      - redis
    volumes:
      - main_certs_data:/etc/letsencrypt
    ports:
<<<<<<< HEAD
      - ${EXTERNAL_HTTP_PORT:-80}:80
=======
      - ${EXTERNAL_HTTP_PORT:-80}:8080
>>>>>>> master
      - ${EXTERNAL_HTTPS_PORT:-443}:443
    environment:
      - ACME_DOMAINS=${ACME_DOMAINS}
      - ACME_EMAIL=${ACME_EMAIL}
