volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  nats_data:
    driver: local
  main_data:
    driver: local

services:
  db:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_db:latest
    restart: always
    shm_size: 256mb
    command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      TZ: Asia/Shanghai
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${EXTERNAL_DB_PORT:-5432}:5432

  redis:
    build:
      context: ..
      dockerfile: docker/redis/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_redis:latest
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis_data:/data
    ports:
      - ${EXTERNAL_REDIS_PORT:-6379}:6379

  minio:
    build:
      context: ..
      dockerfile: docker/minio/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_minio:latest
    command: "server /data"
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - minio_data:/data

  nats:
    build:
      context: ..
      dockerfile: docker/nats/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_nats:latest
    command: "-js -c /etc/nats/nats-server.conf"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - nats_data:/data/jetstream

  main:
    build:
      context: ..
      dockerfile: docker/main/DockerfileDev
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/chat_session_archive_main_dev:latest
    restart: always
    command: "/usr/sbin/sshd -D"
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - db
      - redis
      - minio
      - nats
    tty: true
    ports:
      - ${EXTERNAL_HTTP_PORT:-80}:8080
      - ${EXTERNAL_SSH_PORT:-22}:22
      - ${EXTERNAL_GRPC_PORT:-9001}:9001
    volumes:
      - main_data:/var/www/
