version: "3"

logs:
  mode: production
  level: info
  encoding: console
  use_local_time: true
  output: stdout
  err_output: stdout

rpc:
  listen: tcp://127.0.0.1:6001

# 管理进程的插件
service:
  start-module:
    command: php php/yii start-module
    service_name_in_logs: true
    remain_after_exit: false

