version: "3"

logs:
  mode: production
  level: into
  encoding: console
  use_local_time: true
  output: stderr
  err_output: stderr

server:
  command: php php/yii

http:
  access_logs: true
  max_request_size: 100 # HTTP请求队列超过100个就丢弃，防止服务器压力过大
  pool:
    max_jobs: 100   # 单个worker最大处理请求数,超过后重启
    supervisor:
      max_worker_memory: 128 # 当进程使用内存超过128MB后自动重启(不会终止正在处理的请求)
      ttl: 300s # 每隔5分钟自动重启进程（不会终止正在处理的请求）
      exec_ttl: 30s  # 请求最长执行时间为30秒，超过就自动重启进程以便结束请求
  middleware: ["headers", "gzip", "static"]
  headers:
    response:
      "Cache-Control": "no-cache"
  static:
    forbid: [ ".php", ".htaccess" ]
    calculate_etag: true
    weak: false

# 封装minio上传的插件
minio:
  server_address: minio:9000
  bucket_name: download
  access_key_id: minioadmin
  secret_access_key: minioadmin

# 管理进程的插件
service:
  init-module:
    command: php php/yii init-module
    service_name_in_logs: true
    remain_after_exit: false

